### ISSUE TITLE
Define REST API

### ISSUE THREAD

**Issue by bpmweel** [eWaterCycle/experiment-launcher#1]
Define a rest API that the globe-experiment-finder can use, see https://github.com/eWaterCycle/globe-experiment-finder/issues/10

**Comment by sverhoeven** [comment]
Request should contain a JupyterHub token

**Comment by sverhoeven** [comment]
The request should also contain a username so the notebook can be created in that users home dir.

**Comment by bpmweel** [comment]
https://app.swaggerhub.com/apis/NLeSC/experiment-launcher-api/0.1.0

**Comment by sverhoeven** [comment]
Connexion (https://github.com/zalando/connexion) can not handle OpenApi v3, created v2 based [swagger.yaml](https://github.com/eWaterCycle/experiment-launcher/blob/master/ewatercycle_experiment_launcher/swagger.yaml)

**Comment by sverhoeven** [comment]
In be57ad268c2d2f4e42475077c2e452e5f11b0aa9 the spec is in OpenApi v3 format.
