### ISSUE TITLE
Generate Experiment Notebook

### ISSUE THREAD

**Issue by bpmweel** [eWaterCycle/experiment-launcher#2]

**Comment by sverhoeven** [comment]
At Notebook can be constructed using the http://nbformat.readthedocs.io/en/latest/ Python library

**Comment by sverhoeven** [comment]
As of 25b693d9cb481d4c25bc5889d5ea1fe67e96916c there are 2 different notebook the launcher can generate. 
1. /hello, Print Hello world
2.  /opendap, Opens opendap dataset using xarray

**Comment by sverhoeven** [comment]
A notebook which uses grpc4bmi to run a model is at /bmi endpoint.
