### ISSUE TITLE
Copy Experiment to Notebook User Directory

### ISSUE THREAD

**Issue by bpmweel** [eWaterCycle/experiment-launcher#3]

**Comment by sverhoeven** [comment]
In JupyterLab the file browser has an upload button and new folder button, we could use the server endpoints to copy the notebook.

**Comment by sverhoeven** [comment]
A Notebook/lab has a Swagger API, see https://github.com/jupyter/notebook/blob/master/notebook/services/api/api.yaml

**Comment by sverhoeven** [comment]
There is a JS client for the Jupyter services REST APIs at https://github.com/jupyterlab/jupyterlab/tree/master/packages/services

**Comment by sverhoeven** [comment]
Successfully used a JupyterHub service token to create a directory and document in someones Jupyter Lab, see https://github.com/eWaterCycle/infra/tree/master/JupyterHub#call-api-as-service

**Comment by sverhoeven** [comment]
The request must contain a username, directory and filename. 

The notebook is copied to the Jupyter Lab server of the user in the supplied directory and with supplied filename as of 31b2b0f6c51e834660f102e8f21be79418b538ba
