### ISSUE TITLE
Launch JupyterLab on JupyterHub

### ISSUE THREAD

**Issue by bpmweel** [eWaterCycle/experiment-launcher#4]
Use JupyterHub REST API https://jupyterhub.readthedocs.io/en/latest/reference/rest.html

**Comment by sverhoeven** [comment]
The launcher should be an Externally-Managed Services for JupyterHub see https://jupyterhub.readthedocs.io/en/latest/reference/services.html

**Comment by sverhoeven** [comment]
Tested using service with minikube based hub, see https://github.com/eWaterCycle/infra/blob/master/JupyterHub/README.md#call-api-as-service

**Comment by bpmweel** [comment]
I just saw a talk by Jason Hamman at the EGU, they are building a similar system, their platform focusses on analyses and re-analyses and not model/simulation running though.

https://github.com/pangeo-data

You can try their system at http://pangeo.pydata.org, it uses xarray with a dask cluster to run computations in parallel.

They have a helm script to set up the infrastructure here: https://github.com/pangeo-data/helm-chart

**Comment by sverhoeven** [comment]
Before notebook is copied a server is started using the JupyterHub REST API at https://github.com/eWaterCycle/experiment-launcher/blob/master/ewatercycle_experiment_launcher/hub.py#L17 since 31b2b0f6c51e834660f102e8f21be79418b538ba
