### ISSUE TITLE
Open specific experiment notebook after launch.

### ISSUE THREAD

**Issue by bpmweel** [eWaterCycle/experiment-launcher#5]
https://github.com/jupyterlab/jupyterlab/pull/3396

**Comment by sverhoeven** [comment]
For example for experiment with id `foo` will get url like `/lab/tree/foo/experiment.ipynb`

**Comment by sverhoeven** [comment]
In a JupyterHub the url will be something like `http://192.168.99.100:31053/user/sverhoeven/lab/tree/experiment1/mynewfile.txt`

**Comment by sverhoeven** [comment]
Hmm, the hub url does not work. it does not open the file.

**Comment by sverhoeven** [comment]
Seems JupyterHub/Lab is working with deep url now.

Implementation at https://github.com/eWaterCycle/terriajs/blob/master/lib/ReactViews/FeatureInfo/FeatureInfoExperimentStarter.jsx#L74 opens the correct notebook.
